version: '3.9'

services:
  postgres-qa:
    container_name: experiencia-significativa-API-qa
    build:
      context: ../..     
      dockerfile: Dockerfile 
    restart: always
    env_file:
      - .env.qa
    ports:
      - "5001:5000"
    networks:
      - network_experiencesig
   
    labels:
      - com.experienciasig.environment=qa

networks:
 network_experiencesig:
    external: true


