version: '3.9'

services:
  postgres-staging:
    container_name: experiencia-significativa-API-staging
    build:
      context: ../..      
      dockerfile: Dockerfile 
    restart: always
    env_file:
      - .env.staging
    ports:
      - "5434:5432"
    networks:
      - network_experiencesig

    labels:
      - com.experienciasig.environment=staging

networks:
  network_experiencesig:
    external: true


