version: '3.9'

services:
  postgres-prod:
    container_name: experiencia-significativa-postgres-prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.prod
    ports:
      - "5435:5432"
    networks:
      - network_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - "./backups/prod:/backups/postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - com.experienciasig.group=experienciasig
      - com.experienciasig.environment=prod

networks:
  network_prod:
    driver: bridge

volumes:
  postgres_data_prod:
