version: "3.8"

services:
  # 🌐 API principal - PROD
  exp-api-prod:
    container_name: experiencia-api-prod
    build:
      context: ../..
      dockerfile: API/Dockerfile
    restart: always
    env_file:
      - .env.prod
    ports:
      - "5103:8080"
    networks:
      -  network_experiencesig
    labels:
      - com.gescomph.environment=prod

volumes:
  sqldata_prod:

networks:
  network_experiencesig:
    external: true


