version: '3.9'

services:
  postgres-prod:
    container_name: experiencia-significativa-API-prod
    build:
      context: ../..     
      dockerfile: Dockerfile 
    restart: always
    env_file:
      - .env.prod
    ports:
      - "5003:5000"
    networks:
      - network_experiencesig
   
   
    labels:
      - com.experienciasig.environment=prod

networks:
  network_experiencesig: 
    external: true


